# Powerline style with Kanagawa Paper Ink color palette

format = """
\n[░▒▓](sumi_ink)\
$os\
[](bg:sumi_ink_light fg:sumi_ink)\
$directory\
[](bg:wave_blue fg:sumi_ink_light)\
$git_branch\
$git_status\
$git_metrics\
[](bg:wave_blue_light fg:wave_blue)\
$c\
$elixir\
$elm\
$golang\
$python\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$swift\
[](fg:wave_blue_light)
$status
"""

scan_timeout = 50
command_timeout = 1000
add_newline = false
palette = 'kanagawa'

[palettes.kanagawa]
sumi_ink = '#1F1F28'
sumi_ink_light = '#2A2A37'
wave_blue = '#363646'
wave_blue_light = '#435965'
fuji_white = '#DCD7BA'
autumn_red = '#c4746e'
carp_yellow = '#c4b28a'
autumn_green = '#699469'
spring_violet = '#a292a3'
wave_aqua = '#8ea49e'

# username, host and OS
[username]
style_root = 'bg:sumi_ink fg:autumn_red'
style_user = 'bg:sumi_ink fg:fuji_white'
format = '[$user]($style)'
show_always = true
disabled = false

[hostname]
ssh_only = false
ssh_symbol = ' '
trim_at = '.'
format = '[$hostname$ssh_symbol]($style)'
style = 'bg:sumi_ink fg:fuji_white'
disabled = false

[os]
format = '[ $symbol ]($style)'
style = 'bg:sumi_ink fg:carp_yellow'
disabled = false
# for symbols look at the end of the file

# directory
[directory]
truncation_length = 1
truncate_to_repo = true
format = '[ $path ]($style)[$read_only]($read_only_style)'
style = 'bg:sumi_ink_light fg:fuji_white'
disabled = false
read_only = ' 󰌾 '
read_only_style = 'bg:sumi_ink_light fg:autumn_red'
truncation_symbol = ''

[directory.substitutions]
'Documents' = '󰈙'
'Dokumente' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Musik' = ' '
'Pictures' = ' '
'Bilder' = ' '
'Projects' = ' '

# git
[git_branch]
symbol = ''
style = 'bg:wave_blue fg:wave_aqua'
format = '[ $symbol $branch ]($style)'

[git_status]
style = 'bg:wave_blue fg:wave_aqua'
format = '[$all_status$ahead_behind ]($style)'

[git_metrics]
added_style = 'bg:wave_blue fg:autumn_green'
deleted_style = 'bg:wave_blue fg:autumn_red'
format = '[+$added ]($added_style)[-$deleted ]($deleted_style)'
disabled = false

# programming
[c]
symbol = ' '
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = ' '
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ' '
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ' '
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ' '
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) (\($virtualenv\)) ]($style)'

[gradle]
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ' '
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ' '
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ' '
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ''
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = '󰆥 '
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ''
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ' '
style = 'bg:wave_blue_light fg:spring_violet'
format = '[ $symbol ($version) ]($style)'

[swift]
symbol = ' '
style = 'bg:wave_blue_light fg:#F05239'
format = '[ $symbol ($version) ]($style)'

# status
[status]
format = '[ $symbol ]($style)'
style = "bold"
symbol = '[❯](bold red)'
success_symbol = '[❯](bold green)'
not_executable_symbol = '[🛇](fg:autumn_red)'
not_found_symbol = '[󰍉](fg:autumn_red)'
sigint_symbol = '[](fg:carp_yellow)'
signal_symbol = '[](fg:autumn_red)'
disabled = false

# OS symbols
[os.symbols]
Alpaquita = ' '
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = '󰈸 '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = '󰈺 '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
Redox = '󰀘 '
Solus = '󰠳 '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = '󰍲 '
